### ISSUE TITLE
Custom module development

### ISSUE THREAD

**Issue by shade33** [volatiletech/authboss#148]
Hi!

I need to implement Change Password functionality and I thought develop it as a module for authboss is good idea. But I need response class available  for it. Unfortunately this class is internal within authboss. What is the best way for my task? Did you think about user custom modules for authboss?

**Comment by jack-chung** [comment]
I don't think there's support for custom modules. The only extension points are the storer interfaces and events.

There is an UpdatePassword function in authboss already. I did need to implement my own change password because I wanted the user to verify the current password first, and also to check minimum complexity on the new password. However, I just did it as my own controller action, not part of authboss.

**Comment by aarondl** [comment]
Hey @shade33. Extra modules are supported. Moreso in version 2. Though as @jack-chung mentioned, this is functionality that exists today. What kind of functionality were you looking at providing?

**Comment by thiagocaiubi** [comment]
Hi @aarondl, first of all thanks for authboss. 👍 

I was wondering how to get an IP Whitelist with authboss.
How is the more proper way to achieve this feature? Can I write a custom module or should I work with callbacks only?

**Comment by aarondl** [comment]
@thiagocaiubi Typically you should send this kind of request to the mailing list. Are you talking about an IP Whitelist for user's authentication? If so you should create a module of your own, add storage requirements to have the IP Whitelist table/array available somehow, and then do a hook `BeforeAuth` I think it's called.

**Comment by aarondl** [comment]
Going to close this issue as it's mostly questions.
