### ISSUE TITLE
resend email confirmation

### ISSUE THREAD

**Issue by jmhodges** [volatiletech/authboss#153]
Is there a way to resend the email confirmation link? It'd be nice if this was just a known endpoint already.

**Comment by aarondl** [comment]
No there actually isn't. This would be a good place for a pull request :)

https://github.com/volatiletech/authboss/blob/master/confirm/confirm.go#L83

You can see that the confirm module only has one endpoint and that's to actually confirm the tokens it creates.

**Comment by aarondl** [comment]
You should be able to do this now by calling this method:
https://github.com/volatiletech/authboss/blob/9ef2a06dcb6a99b2a33817131e506ee3fd695988/confirm/confirm.go#L110

Is this sufficient? It requires that you have an authboss instance, and use that to create a `Confirm` instance before you can call the method (since config etc. is given in that way), but I think that's pretty reasonable. Thoughts?

**Comment by aarondl** [comment]
The above should work. Let me know if there's any problems with the approach.

**Comment by rbren** [comment]
For posterity, here's what I had to do:

```go
 ab := authboss.New()
/* set up authboss */
confirmer := confirm.Confirm{Authboss: auth}
router.HandleFunc("/resend-confirmation", func(w http.ResponseWriter, r *http.Request) {
    user, err := auth.CurrentUser(r)
    if err != nil {
        handleNotAuthorized(w, r)
        return
    }
    confirmer.StartConfirmation(r.Context(), user.(authboss.ConfirmableUser), true)
    getDataAndSendTemplate(w, r, db, "auth/resend-confirmation.html")
})
```
