### ISSUE TITLE
logout should require a POST

### ISSUE THREAD

**Issue by jmhodges** [volatiletech/authboss#154]
A user clicking a link to the logout page will log them out. A malicious user can then logout anyone by getting them to click a link to it.

It should require a POST instead. What are now currently logout links would become buttons.

**Comment by aarondl** [comment]
This seems like it has some logic behind it. The reason it wasn't this way from the beginning was because logging out didn't seem that damaging, but also because POST is kind of annoying since you either need Javascript or magic CSS to make your button look like a link (if that's what you wanted) or what have you. We could definitely change this though.

**Comment by aarondl** [comment]
This is now configurable:
https://github.com/volatiletech/authboss/blob/9ef2a06dcb6a99b2a33817131e506ee3fd695988/auth/auth.go#L42

With a default of DELETE method (though you could configure it to be POST or GET):
https://github.com/volatiletech/authboss/blob/9ef2a06dcb6a99b2a33817131e506ee3fd695988/config.go#L144

Considering this closed as it won't be backported to v1 and the code exists and should function.
