### ISSUE TITLE
v2 Release

### ISSUE THREAD

**Issue by danikarik** [volatiletech/authboss#167]
Hi! I was reviewing code in vcrazy branch (future v2) and got a question when you will publish it?

**Comment by indpnday** [comment]
Except a few issues, we are using vcrazy branch in our code and we are very happy with it :smile: Amazing work with the new plugin design.

**Comment by danikarik** [comment]
I thought to use it in current form, but maybe stable version is coming soon)

**Comment by aarondl** [comment]
@danikarik I'll publish it when it's ready. Which should be shortly-ish. Just need to finish implementing the sample with the new code to verify the new design isn't bad in some way that I didn't predict. So far it's gone well and I don't foresee any more majorly breaking changes. If you were to start using it now, you might have to suffer a rename or something at my whims because I still have the license to do so. But no big restructuring if I can avoid it.

@indpnday I'm surprised (and pleased) to hear someone's using it and the positive feedback is very appreciated. Can you elaborate on some of the issues you ran into? I'd love to know if there's something that I should fix prior to v2 landing just in case there's breakages.

**Comment by indpnday** [comment]
@aarondl Mainly the lack of a finished example. We had to read a lot of your code to understand how to use it. But it's not a problem! We know that you are working on the new version and we didn't want to bother you with false bugs. We understand that you haven't finish it :-)

For example, the Logout plugin, requires this to work:

```
func init() {
authboss.RegisterModule("register", &Register{})
}
```

We are waiting to the release of the v2 to see if we need to open file bugs or PR.

**Comment by aarondl** [comment]
https://github.com/volatiletech/authboss/releases/tag/v2.0.0-rc2

I'll just leave this here. Please join the mailing list so as not to miss out an announcments like this in the future :)
Link in the README

**Comment by aarondl** [comment]
Link to the release post on mailing list which has some extra info:
https://groups.google.com/a/volatile.tech/forum/#!topic/authboss/SBfx0Bc5PNE
