### ISSUE TITLE
Using Storer interface with MySQL

### ISSUE THREAD

**Issue by hinsxd** [volatiletech/authboss#169]
I read though the storer example and it was using MemStorer.
If I want to use MySQL for my website to handle user Login/Register, do I only need to modify the storer.go and write a new set of functions for MySQL reading / writing (with the same function name of course) instead of MemStorer?
I will be so glad if there is some opensource example of such approach because I am not confident in writing code from scratch. Or do Gophers use MySQL often? Do they have better approach to backup-able data storage?

**Comment by aarondl** [comment]
People who write Go quite often use MySQL. Typically via this driver: https://github.com/go-sql-driver/mysql

If you know how to work with Go and MySQL you shouldn't have much trouble replacing the MemStorer. Keep in mind it's implementing the authboss.ServerStorer interface, so the method names and arguments can't change. But your new type (let's called it MySQLStorer) needs to implement the same operations (Load/Save etc) but using MySQL instead of some random map in memory.

It sounds like you're not very comfortable with Go, but Authboss actually requires you to write quite a bit of code from scratch to fullfill [it's 
many interfaces](https://github.com/volatiletech/authboss/tree/v2#storage-and-core-implementations). I don't want to discourage you but you definitely have to be comfortable with Go and especially interfaces to be able to use Authboss.

These interfaces abstract "a website" and allow authboss to integrate well with whatever you're creating. But implementing all these interfaces is not completely trivial. There are default implementations in the `defaults` package for most of them, but not all.

To see the requirements for the use cases you'd like to implement you can check the documentation here:
https://github.com/volatiletech/authboss/tree/v2#user-auth-via-password
https://github.com/volatiletech/authboss/tree/v2#user-registration

As far as I'm aware there is no open source implementations to look at other than the sample.

**Comment by hinsxd** [comment]
Yes I come from the python world with tons of out-of-the-box examples. Especially for user authentication I was really expecting detailed mature samples with different implementations, because security is one of my greatest concern.
Thanks for letting me know. It's quite challenging but I am definitely glad to try writing and improving.

**Comment by aarondl** [comment]
Closing this. Let me know if you have any other questions. The mailing list is honestly a better place for things like this, there's a link on the v2 readme. :)
