### ISSUE TITLE
Getting Cookies out of custom Autoboss V2 renderer

### ISSUE THREAD

**Issue by punkle64** [volatiletech/authboss#172]
In my own custom authboss V2 renderer I'm trying to get a cookie ("lang" - which, I checked, is in my browser with value "it"). But I somehow fail to do so and get the default "en". I think I'm doing it wrong and I also think that a good cookie-getting-example for people would be useful.

So here's my code:

```
func (h *HTML) Render(ctx context.Context, page string, data authboss.HTMLData) (output []byte, contentType string, err error) {
  var lang string
  var current abclientstate.CookieState
  cookieIntf := ctx.Value(authboss.CTXKeyCookieState)
  if cookieIntf == nil {
    current = abclientstate.CookieState{}
  } else {
    current = cookieIntf.(abclientstate.CookieState)
  }
  lang, ok := current.Get("lang")
  if !ok {
    lang = "en"
  }
  data.MergeKV("lang", lang)
  ...
```

How should it be instead? BTW for non-authboss templates I use the request to get the cookie, and it works just fine like this:

```
func mustRender(w http.ResponseWriter, r *http.Request, name string, data authboss.HTMLData) {
  var lang string
  lang_cookie, err := r.Cookie("lang")
  if err != nil {
    lang = "en"
  } else {
    lang = lang_cookie.Value
  }
  ...
```

Thank you in advance for any help you'll be willing to give me,

Cheers,
Daniele

**Comment by aarondl** [comment]
So, the authboss cookiestate stuff is really only for authboss cookies. For your own cookies you should be reading the request directly like you're doing in the bottom code. The question you have to answer is: How do you pass this to the `Renderer` since you have no `*http.Request` object there.

One of the things the default `Responder` interface does (the interface responsible for deciding how to respond to a given request, which usually involves calling the renderer after doing some things) is it takes the data that's been put in the context, and merges it with the data the authboss page wants to render. This means you can inject any value you want by supplying an `authboss.HTMLData` in the `context.Context` of your request: https://github.com/volatiletech/authboss/blob/v2/defaults/responder.go#L28

So the full solution would look like:
1. Create a middleware that takes the cookie value you want and shoves it into the context with the key `authboss.CTXKeyData`. Be careful to merge the data if some exists in the context already.
1. Put this new middleware in your middleware stack above any `authboss` routes.
1. In your renderer, the data should already be good to go (provided you're using the `defaults.Responder`, otherwise you have to duplicate the context/data merging I showed you).

Hopefully that helps. I'll consider the issue closed because I'm certain this can/will work. But if you require any clarification just continue conversation here on the closed issue. :)

**Comment by punkle64** [comment]
Thank you very much! Your suggestion worked perfectly. For anyone who's interested, this is the middleware I wrote for getting the cookie:

```
func AbLangCookieMiddleware(ab *authboss.Authboss) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
      var lang string
      lang_cookie, err := r.Cookie("lang")
      if err != nil {
      	lang = "en"
      } else {
        lang = lang_cookie.Value
      }
      var current authboss.HTMLData
      dataIntf := r.Context().Value(authboss.CTXKeyData)
      if dataIntf == nil {
      	current = authboss.HTMLData{}
      } else {
      	current = dataIntf.(authboss.HTMLData)
      }
      current.MergeKV("lang", lang)
      ctxWithNewData := context.WithValue(r.Context(), authboss.CTXKeyData, current)
      r = r.WithContext(ctxWithNewData)
		  next.ServeHTTP(w, r)
		})
	}
}
```
