### ISSUE TITLE
V2 odd numbers odd fields in validator?

### ISSUE THREAD

**Issue by IvRRimum** [volatiletech/authboss#178]
I am a bit lost here, why does the validatable fields need to be odd?

```
func (h HTTPFormValidator) Validate() []error {
	var errList authboss.ErrorList

	for _, rule := range h.Ruleset {
		field := rule.FieldName

		val := h.Values[field]
		if errs := rule.Errors(val); len(errs) > 0 {
			errList = append(errList, errs...)
		}
	}

	if l := len(h.ConfirmFields); l != 0 && l%2 != 0 {
		panic("HTTPFormValidator given an odd number of confirm fields")
	}
```

I am trying to add secret answer(Whats your pets name?) to the recover/end, having a bit of issues with this one.

**Comment by aarondl** [comment]
`ConfirmFields` is a bit of a weird piece. It takes a list of `fieldName, confirmFieldName` but instead of a struct or array of 2 elements or whatever, it just uses a single flattened slice.

As an example:

```go
ConfirmFields = []string{"password", "confirm_password", "email", "confirm_email"}
```

This will make sure that the `password` field matches the `confirm_password` field in the body of the request and the same of e-mail.

Also still happy to carry these sorts of questions etc. to the mailing list. This generates a lot of spam in the wrong places.
https://groups.google.com/a/volatile.tech/forum/#!forum/authboss
