### ISSUE TITLE
Reason for panic in confirm middleware

### ISSUE THREAD

**Issue by wezzle** [volatiletech/authboss#192]
What is the reason for triggering a panic in the confirm middleware if no user can be retrieved from the session? [See here](https://github.com/volatiletech/authboss/blob/master/confirm/confirm.go#L255)

Now it's impossible to use the confirm.Middleware on any route that does not require a user to be logged in.

I would suggest the following edit for above mentioned line:
```go
user, err := ab.LoadCurrentUser(&r)
if err != nil {
	panic(err)
}

// Skip if there is no user in session
if user == nil {
	next.ServeHTTP(w, r)
	return
}
```

This could however break some things for people expecting the panic to run when the user is not logged in.

 Really like to hear your thoughts on this.

**Comment by aarondl** [comment]
This is to force efficiency and protect invariants. There's no reason that a route that is not a protected resource should ever run many middlewares (eg. `confirm`, `lock` etc). The panic is there to force you to put something that loads the user before them and to report errors. I'll elaborate a bit more on these reasons:

1. Forces you to do the best thing and never run this middleware (which is useless in the context of an unauthenticated route) if a user is not logged in, it expects that there's a middleware higher up the stack that gets the current user and stops the middleware chain (and the response) if he doesn't exist/is not logged in.
1. Middlewares have no way of reporting errors, if the user fails to load for whatever reason, I don't know of any http-stack-agnostic way to handle that.
1. For efficiency in a middleware chain for a protected route many things will query the user so it's good to get the user loaded and "cached" in the context right away so that `confirm` and `lock` etc. do no database operations.

I guess maybe your problem is that you have a page that can be viewed by a logged in user or a guest, but IF the user is logged in you want to ensure he's confirmed right?

**Comment by wezzle** [comment]
Yes I can understand the reasoning behind that.

For now I'm still in a testing setup to explore all the different parts of Authboss so I'm not certain my current use case will ever be relevant for a production environment. Your guess is correct because I now have a page `/whoami` that returns the email of the user that is logged in, so possibly it returns nothing because the user is not logged in. Because I wanted to test the functionality of the confirm packages I ended up putting it in-front of this page triggering the panic when the user is not logged in.

You can close the issue then, your explanation is correct and my current use-case is not really standard.

Thank you

**Comment by aarondl** [comment]
Keep in mind you can easily replicate this confirm middleware functionality if you needed it to do something different too :)

**Comment by wezzle** [comment]
Yes I've done just that, but while doing it I was uncertain of the reasoning behind the panic. So that is cleared up now
