### ISSUE TITLE
gin compatibility

### ISSUE THREAD

**Issue by aight8** [volatiletech/authboss#193]
Currently authboss is not compatible with gin, it‘s even throws an error when a middle adapter.
I have not located the error currently but the ResponseWriter don‘t implement some interfaces.
The goal should be that gin should work with an http middleware adapter seamlessly.
That the abstraction layer should be adjusted. It should be more flat.

**Comment by aarondl** [comment]
Hey there. Gin compatibility is not really a goal. The abstractions that are in authboss allow you to integrate with whatever http stack. Even ones that wrap the response writer as there is a way to get an underlying response writer via [this interface](https://github.com/volatiletech/authboss/blob/master/client_state.go#L71).

As it stands this issue is not useful as it does not address specific concerns with the abstractions in authboss nor where the incompatibilities with Gin begin. The ResponseWriter does in fact implement the required interfaces of the Go standard library http package so there must be some hidden Gin requirements you're running into.

Please feel free to re-open with concrete details of the problem or a proposal on how the abstractions could be improved.
