### ISSUE TITLE
Why CurrentUser works and r.Context().Value("user") don't?

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#206]
I'm using this code:

```go
router.Use(ab.LoadClientStateMiddleware)

router.Group(func(subrouter chi.Router) {
	subrouter.Use(authboss.Middleware2(ab, 1, 1))
	subrouter.Get("/", func(w http.ResponseWriter, r *http.Request) {
		user, _ := ab.CurrentUser(r)
		fmt.Println(user)
	}
}
```

and it print `user` correctly.

If I use this code it doesn't work: the user is `nil` every time. **Why?**

```go
router.Use(ab.LoadClientStateMiddleware)

router.Group(func(subrouter chi.Router) {
	subrouter.Use(authboss.Middleware2(ab, 1, 1))
	subrouter.Get("/", func(w http.ResponseWriter, r *http.Request) {
		if user := r.Context().Value("user"); user != nil {
			fmt.Println(user.(auth.User))
		} else {
			fmt.Println("Still nil")
		}
	}
}
```

**Comment by aarondl** [comment]
The reason is that the user has to first be placed in that context. CurrentUser both looks up the user ID in the session but also loads him from the database which is why it works.

Only if Load User has been called previously would your context lookup work.

**Comment by frederikhors** [comment]
If I debug the `ctx` contains user:

![image](https://user-images.githubusercontent.com/41120635/50558958-7e2ce080-0cf2-11e9-9572-f255529bbfc2.png)

I tried now in an external `func`: same problem.

`Only if Load User has been called previously would your context lookup work.`

This was already called.

**What can it be, @aarondl?**

**Comment by aarondl** [comment]
When using context keys it is a best practice to use an unexported type to create context keys with. This prevents other packages from accidentally altering or otherwise accessing values inside the context.

https://github.com/volatiletech/authboss/blob/master/context.go

Because your user string does not have the contextKey wrapper type it can never retrieve the value.

You must retrieve it using authboss.CTXKeyUser
