### ISSUE TITLE
Inconsistent behavior of PID?

### ISSUE THREAD

**Issue by raven-chen** [volatiletech/authboss#229]
Shall `GetPID` equals the `key string` parameter in the AuthStorer `Load` interface?

the `GetPID` should return the primary key of the model, which is ID. but when login with email, the `key` in `Load(ctx context.Context, key string)`  is `email`. Have I understood it incorrectly? I have to manually determine the `key` to perform different query. it looks quite ugly.

```
func (s AuthStorer) Load(ctx context.Context, key string) (authboss.User, error) {
	uid, convertErr := strconv.Atoi(key)
	var user models.User

	if convertErr == nil {
		if err := db.DB.First(&user, uid).Error; err != nil {
			return &user, authboss.ErrUserNotFound
		}
	} else {
		if err := db.DB.Where("email = ?", key).First(&user).Error; err != nil {
			return &user, authboss.ErrUserNotFound
		}
	}

	return &user, nil
}
```

**Comment by aarondl** [comment]
GetPID is not actually supposed to return the user ID. It's meant to be the string that the user uses to identify themselves on your site. That's typically username or e-mail, it could be an ID, but the user would need to know that.

This is because when a user comes to the login form, they put in their details: example@example.com / pass1234, it sends this into Load() and expects to get a user back using that string. Let me know if you have further questions about it.
