### ISSUE TITLE
incorrect requests return status code 200

### ISSUE THREAD

**Issue by fgehrlicher** [volatiletech/authboss#234]
Many endpoints return http status 200 in case of a faulty request (like wrong credentials or invalid recovery token). Is that behavior intended?

**Comment by aarondl** [comment]
This is when in api mode?

**Comment by aarondl** [comment]
It's intentional. It's sort of a side effect from it being able to support both JSON and HTML Forms. In that that same error would be a 200 OK in an HTML Form response.

In our applications we'll simply do a conditional JSON parse, if `"status": "true"` key and value exist then we know to parse it as an authboss JSON error (mostly the format you're looking at there).

Authboss doesn't really try to be a restful API and use status codes to indicate problems with user information for application level issues, only request/protocol/server level issues (bad requests for an form post, internal server errors etc). Analyzing the response is the only way to know if something went wrong.

**Comment by fgehrlicher** [comment]
ok that reasonable. thank you for clarifying!

**Comment by frederikhors** [comment]
Is this related to [this](https://github.com/volatiletech/authboss/issues/248), @fgehrlicher?
