### ISSUE TITLE
Looking for a practical storer that is ready to deploy

### ISSUE THREAD

**Issue by wkoszek** [volatiletech/authboss#321]
Authboss looks very good. Is there any published "storer" that supports a practical DB? I was thinking PostgreSQL or Redis. I wonder why no ready-to-use implementations exist so far.

**Comment by aarondl** [comment]
There's none that I'm aware of. I think the reasoning is most people create their storers using their ORM-like layer that isn't very generic to everybody's code base rather than trying to create one using the `database/sql` library directly. It's also true that everybody's columns are a little bit different, some people use uuid columns for ids, some use `serial` so it might be difficult to use unless you're starting a project from complete scratch.

Try using Github Discussions for these sorts of non-bug conversation type things :)
