### ISSUE TITLE
Inconsistency between authboss and authboss-sample

### ISSUE THREAD

**Issue by jack-chung** [volatiletech/authboss#90]
The doc for Storer.Put() says this should be update only, not create. But the sample app implements it by calling Create().

**Comment by kris-runzer** [comment]
The sample is what it is, just a sample.  Hence, that is why we put the massive disclaimer on the README.md:

> Disclaimer: This sample is NOT a seed project. Do not use it as one. It is used as an example of how to use the Authboss API. This means if you copy-paste code from this sample you are likely opening yourself up to various security holes, bad practice, and bad design. It's a demonstration of the surface API of Authboss and how the library can be used to make a functioning web project, to use this sample as anything else is malpractice.

By all means though, if you would like to fix it submit a pull request :)

**Comment by aarondl** [comment]
This is a doc issue, we should be clear on what we mean. I'll fix this eventually.

**Comment by cgag** [comment]
Whats the point of having a sample that contains security holes?  If it's easy to use this library incorrectly, then a sample that does things right seems pretty important.

**Comment by aarondl** [comment]
@cgag Unfortunately security code is hard. We've put a lot of work into it to make sure it's correct, follow best practices and welcome any third party auditing.

However there's a chance we got it wrong, and this disclaimer is a "cover our ass" type of thing. It's not hard to use Authboss properly in my opinion, but
you should know what you're doing and we don't cover every seam for you because we can't and it's outside the scope of the project.

We've done some bad things like hard code passwords, put secret keys in the code instead of in config files, left secrets in log files etc. We did all this stuff
in order to quickly show off the API without exposing users to too much extraneous code that would confuse them. This is why we make such a disclaimer.

**Comment by jack-chung** [comment]
I think the sample app does a good job of showing the features of authboss and how to use them. It would be good to add more comments in the sample code to say something to the effect of "here's what you should do differently in production". The disclaimer does make me nervous and wonder what parts am I missing or doing wrong.

**Comment by aarondl** [comment]
I don't know that the docs are that bad currently (see v2 branch of sample).
